Repository sharetribe/ftw-daily, pull requests merged in 2018-08, with the labels that each got.

#877 Reusable map container
  CHANGELOG.md
  src/components/SearchMap/ReusableMapContainer.js
  src/components/SearchMap/SearchMap.css
  src/components/SearchMap/SearchMap.js
  src/containers/SearchPage/SearchPage.css
  src/containers/SearchPage/SearchPage.js
  src/containers/SearchPage/__snapshots__/SearchPage.test.js.snap
Labels: review ok

#876 Fix multi select filters in filter panel
  CHANGELOG.md
  package.json
  src/components/SearchFilters/SearchFilters.js
  src/components/SearchFiltersMobile/SearchFiltersMobile.js
  src/components/SelectMultipleFilter/SelectMultipleFilter.example.js
  src/components/SelectMultipleFilter/SelectMultipleFilter.js
  src/components/SelectMultipleFilterPlain/SelectMultipleFilterPlain.example.js
  src/components/SelectMultipleFilterPlain/SelectMultipleFilterPlain.js
  src/forms/SelectMultipleFilterForm/SelectMultipleFilterForm.js
  src/forms/SelectMultipleFilterPlainForm/SelectMultipleFilterPlainForm.js
Labels: review ok

#882 Reusable SearchMap
  .nsprc
  CHANGELOG.md
  src/components/SearchMap/ReusableMapContainer.js
  src/components/SearchMap/SearchMap.js
  src/components/SearchMapInfoCard/SearchMapInfoCard.js
  src/containers/SearchPage/SearchPage.js
  src/containers/SearchPage/__snapshots__/SearchPage.test.js.snap
Labels: review ok

#887 Extract LocationAutocompleteInputGoogleMaps
  src/components/LocationAutocompleteInput/LocationAutocompleteInput.js
  src/components/LocationAutocompleteInput/LocationAutocompleteInputGoogleMaps.css
  src/components/LocationAutocompleteInput/LocationAutocompleteInputGoogleMaps.js
Labels: review ok

#886 LocationAutocompleteInput with Mapbox support
  src/components/LocationAutocompleteInput/LocationAutocompleteInput.js
  src/components/LocationAutocompleteInput/LocationAutocompleteInputGoogleMaps.css
  src/components/LocationAutocompleteInput/LocationAutocompleteInputGoogleMaps.js
Labels: in progress

#891 Availability for the date range picker
  src/components/FieldDateRangeInput/DateRangeInput.css
  src/components/FieldDateRangeInput/DateRangeInput.helpers.js
  src/components/FieldDateRangeInput/DateRangeInput.js
  src/components/FieldDateRangeInput/FieldDateRangeInput.example.js
  src/components/FieldDateRangeInput/FieldDateRangeInput.js
Labels: review ok

#894 Default location suggestions for LocationAutocompleteInput
  CHANGELOG.md
  docs/google-maps.md
  src/components/LocationAutocompleteInput/GeocoderGoogleMaps.js
  src/components/LocationAutocompleteInput/GeocoderMapbox.js
  src/components/LocationAutocompleteInput/LocationAutocompleteInputImpl.js
Labels: review comments

#895 Autocomplete current location
  CHANGELOG.md
  docs/google-maps.md
  src/components/LocationAutocompleteInput/GeocoderGoogleMaps.js
  src/components/LocationAutocompleteInput/GeocoderMapbox.js
  src/components/LocationAutocompleteInput/IconCurrentLocation.js
  src/components/LocationAutocompleteInput/IconHourGlass.js
  src/components/LocationAutocompleteInput/LocationAutocompleteInput.css
  src/components/LocationAutocompleteInput/LocationAutocompleteInputImpl.js
  src/components/SectionHero/__snapshots__/SectionHero.test.js.snap
  src/components/TopbarDesktop/__snapshots__/TopbarDesktop.test.js.snap
  src/translations/en.json
  src/util/googleMaps.js
  src/util/maps.js
Labels: review comments

#896 Mapbox Map component
  CHANGELOG.md
  src/components/Map/DynamicGoogleMap.js
  src/components/Map/DynamicMapboxMap.js
  src/components/Map/GoogleMap.js
  src/components/Map/Map.js
  src/components/Map/MapboxMap.js
  src/components/Map/StaticGoogleMap.js
  src/components/Map/StaticMapboxMap.js
  src/containers/ListingPage/SectionMapMaybe.js
  src/util/maps.js
Labels: review wanted

#897 Unify default search data and avoid place details API call
  src/components/LocationAutocompleteInput/GeocoderGoogleMaps.js
  src/components/LocationAutocompleteInput/GeocoderMapbox.js
Labels: review ok

#899 Remove Google Maps fullscreen control
  src/components/SearchMap/SearchMap.js
  src/containers/SearchPage/SearchPage.js
  src/containers/SearchPage/__snapshots__/SearchPage.test.js.snap
Labels: review ok

#901 Availability improvements
  CHANGELOG.md
  src/config.js
  src/containers/ListingPage/ListingPage.duck.js
  src/containers/ListingPage/ListingPage.js
  src/containers/ListingPage/SectionBooking.js
  src/containers/ListingPage/__snapshots__/ListingPage.test.js.snap
  src/forms/BookingDatesForm/BookingDatesForm.css
  src/forms/BookingDatesForm/BookingDatesForm.js
  src/translations/en.json
Labels: review ok

#902 Availability environment variable
  .env-template
  docs/env.md
  src/config.js
Labels: review ok

#904 Delay Mapbox lib usage to fix server side rendering
  src/components/LocationAutocompleteInput/GeocoderMapbox.js
  src/components/LocationAutocompleteInput/LocationAutocompleteInputImpl.js
Labels: review ok

#906 Disable default predictions in listing editing wizard
  src/components/LocationAutocompleteInput/LocationAutocompleteInputImpl.js
  src/forms/EditListingLocationForm/EditListingLocationForm.js
Labels: review ok

#907 Add missing bounds for Mapbox places
  src/components/LocationAutocompleteInput/GeocoderMapbox.js
Labels: review ok
