Repository sharetribe/ftw-daily, pull requests merged in 2018-07, with the labels that each got.

#861 Fix clearing tx initial message before the page change is made
  CHANGELOG.md
  src/forms/StripePaymentForm/StripePaymentForm.js
Labels: review ok

#864 Fix contact details form submit button state
  CHANGELOG.md
  src/forms/ContactDetailsForm/ContactDetailsForm.js
Labels: review ok

#863 Add clear errors action
  CHANGELOG.md
  src/containers/TransactionPage/TransactionPage.duck.js
Labels: review comments, review ok

#862 User card layout
  CHANGELOG.md
  src/components/UserCard/UserCard.css
  src/components/UserCard/UserCard.example.js
  src/components/UserCard/UserCard.js
  src/containers/ListingPage/ListingPage.css
  src/containers/ListingPage/ListingPage.js
  src/containers/ListingPage/SectionHost.js
  src/containers/ListingPage/__snapshots__/ListingPage.test.js.snap
Labels: review ok

#865 Change clearErrors action to resetState
  CHANGELOG.md
  src/containers/TransactionPage/TransactionPage.duck.js
Labels: review ok

#866 Improve tx page state management
  CHANGELOG.md
  src/containers/TransactionPage/TransactionPage.duck.js
Labels: review ok

#859 Update Redux to v4
  CHANGELOG.md
  package.json
  yarn.lock
Labels: review ok

#867 Add sessiontoken and sparse fields
  CHANGELOG.md
  src/components/LocationAutocompleteInput/LocationAutocompleteInput.js
  src/util/googleMaps.js
Labels: review comments

#869 Listingpage static map
  CHANGELOG.md
  package.json
  public/static/icons/map-marker-32x32.png
  src/components/Map/DynamicMap.js
  src/components/Map/Map.js
  src/components/Map/StaticMap.js
  src/config.js
  src/containers/ListingPage/ListingPage.css
  src/containers/ListingPage/SectionMapMaybe.js
  src/containers/SearchPage/__snapshots__/SearchPage.test.js.snap
  src/util/contextHelpers.js
  yarn.lock
Labels: review comments

#871 Improve listingpage lazy loading
  CHANGELOG.md
  src/containers/ListingPage/ListingPage.css
  src/util/contextHelpers.js
Labels: review comments

#868 Fetch availability data
  package.json
  src/components/FieldDateInput/DateInput.js
  src/components/FieldDateRangeInput/DateRangeInput.js
  src/config.js
  src/containers/ListingPage/ListingPage.duck.js
  src/containers/ListingPage/ListingPage.js
  src/util/types.js
  yarn.lock
Labels: review comments, review ok

#873 Show available time slots in date input
  src/components/FieldDateInput/DateInput.css
  src/components/FieldDateInput/DateInput.js
  src/components/FieldDateInput/FieldDateInput.example.js
  src/components/FieldDateInput/FieldDateInput.js
  src/containers/ListingPage/ListingPage.js
  src/util/data.js
  src/util/test-data.js
  src/util/types.js
Labels: review comments

#874 Seeded random used on obfuscatedCoordinatesImpl
  CHANGELOG.md
  package.json
  src/util/maps.js
  yarn.lock
Labels: review ok
