Repository sharetribe/ftw-daily, pull requests merged in 2018-12, with the labels that each got.

#961 Improve production setup
  CHANGELOG.md
  README.md
  app.json
  docs/README.md
  docs/assets/deploying-to-production/heroku-config-vars.png
  docs/assets/deploying-to-production/heroku-connect-git.png
  docs/assets/deploying-to-production/heroku-domains.png
  docs/assets/deploying-to-production/heroku-logs.png
  docs/deploying-to-production.md
Labels: review comments

#964 Change supported node version to the latest LTS
  .circleci/config.yml
  CHANGELOG.md
  package.json
Labels: review ok

#967 Update dependencies
  CHANGELOG.md
  docs/env.md
  docs/google-maps.md
  docs/icons.md
  package.json
  public/static/reactDates.css
  src/Routes.js
  src/components/BookingBreakdown/LineItemUnitPrice.js
  src/components/Discussion/Discussion.js
  src/components/EditListingWizard/EditListingWizard.js
  src/components/FieldDateInput/DateInput.css
  src/components/FieldDateInput/DateInput.js
  src/components/FieldDateInput/FieldDateInput.js
  src/components/FieldDateRangeInput/DateRangeInput.css
  src/components/FieldDateRangeInput/DateRangeInput.js
  src/components/FieldDateRangeInput/FieldDateRangeInput.js
  src/components/ListingLink/ListingLink.js
  src/components/ManageListingCard/ManageListingCard.js
  src/components/ManageListingCard/__snapshots__/ManageListingCard.test.js.snap
  src/components/Map/StaticGoogleMap.js
  src/components/RangeSlider/RangeSlider.js
  src/components/SearchFilters/SearchFilters.js
  src/components/SearchMap/SearchMapWithMapbox.js
  src/components/Topbar/Topbar.js
  src/components/TransactionPanel/TransactionPanel.helpers.js
  src/containers/AuthenticationPage/AuthenticationPage.js
  src/containers/CheckoutPage/CheckoutPage.js
  src/containers/ContactDetailsPage/ContactDetailsPage.js
  src/containers/EditListingPage/EditListingPage.js
  src/containers/EmailVerificationPage/EmailVerificationPage.js
  src/containers/InboxPage/InboxPage.js
  src/containers/LandingPage/LandingPage.js
  src/containers/ListingPage/ListingPage.js
  src/containers/ManageListingsPage/ManageListingsPage.js
  src/containers/NotFoundPage/NotFoundPage.js
  src/containers/PasswordChangePage/PasswordChangePage.js
  src/containers/PasswordRecoveryPage/PasswordRecoveryPage.js
  src/containers/PasswordResetPage/PasswordResetPage.js
  src/containers/PayoutPreferencesPage/PayoutPreferencesPage.js
  src/containers/PrivacyPolicyPage/PrivacyPolicyPage.js
  src/containers/ProfilePage/ProfilePage.js
  src/containers/ProfileSettingsPage/ProfileSettingsPage.js
  src/containers/SearchPage/SearchPage.js
  src/containers/StyleguidePage/StyleguidePage.js
  src/containers/TermsOfServicePage/TermsOfServicePage.js
  src/containers/TopbarContainer/TopbarContainer.js
  src/containers/TransactionPage/TransactionPage.js
  src/forms/BookingDatesForm/EstimatedBreakdownMaybe.js
  src/util/contextHelpers.js
  src/util/maps.js
  yarn.lock
Labels: review comments, review ok

#970 Improve per unit translations
  CHANGELOG.md
  src/components/ListingCard/ListingCard.js
  src/components/ListingCard/__snapshots__/ListingCard.test.js.snap
  src/components/ManageListingCard/ManageListingCard.js
  src/components/ManageListingCard/__snapshots__/ManageListingCard.test.js.snap
  src/config.js
  src/containers/ListingPage/SectionBooking.js
  src/containers/ListingPage/SectionHeading.js
  src/forms/EditListingPricingForm/EditListingPricingForm.js
  src/forms/EditListingPricingForm/__snapshots__/EditListingPricingForm.test.js.snap
  src/translations/en.json
  src/translations/fr.json
Labels: review wanted

#968 Add missing stripe countries
  .env-template
  CHANGELOG.md
  src/components/StripeBankAccountTokenInputField/StripeBankAccountTokenInputField.example.js
  src/components/StripeBankAccountTokenInputField/StripeBankAccountTokenInputField.js
  src/components/StripeBankAccountTokenInputField/StripeBankAccountTokenInputField.util.js
  src/config.js
  src/ducks/user.duck.js
  src/forms/PayoutDetailsForm/PayoutDetailsAddress.js
  src/forms/PayoutDetailsForm/PayoutDetailsForm.js
  src/stripe-config.js
  src/translations/en.json
  src/translations/fr.json
  src/util/validators.js
  src/util/validators.test.js
Labels: review ok

#977 Create FieldRadioButton component
  CHANGELOG.md
  src/components/FieldRadioButton/FieldRadioButton.css
  src/components/FieldRadioButton/FieldRadioButton.example.js
  src/components/FieldRadioButton/FieldRadioButton.js
  src/components/index.js
  src/examples.js
Labels: review comments, review ok

#981 Add new translations
  CHANGELOG.md
  src/translations/en.json
  src/translations/fr.json
Labels: in progress

#985 Add image of fork button to deploy guide
  CHANGELOG.md
  docs/assets/deploying-to-production/fork_button.png
  docs/deploying-to-production.md
  ext/default-mail-templates/README.md
Labels: review comments, review ok

#969 Extract booking section from listing page
  CHANGELOG.md
  src/components/BookingPanel/BookingPanel.css
  src/components/BookingPanel/BookingPanel.example.css
  src/components/BookingPanel/BookingPanel.example.js
  src/components/BookingPanel/BookingPanel.js
  src/components/FieldDateRangeInput/DateRangeInput.css
  src/components/FieldDateRangeInput/FieldDateRangeInput.css
  src/components/ListingCard/ListingCard.js
  src/components/index.js
  src/containers/CheckoutPage/CheckoutPage.js
  src/containers/CheckoutPage/__snapshots__/CheckoutPage.test.js.snap
  src/containers/ListingPage/ListingPage.css
  src/containers/ListingPage/ListingPage.js
  src/containers/ListingPage/SectionBooking.js
  src/containers/ListingPage/__snapshots__/ListingPage.test.js.snap
  src/examples.js
  src/forms/BookingDatesForm/BookingDatesForm.css
  src/translations/en.json
  src/translations/fr.json
Labels: review ok

#976 Enable requesting to book straight from enquiry
  CHANGELOG.md
  src/components/BookingPanel/BookingPanel.example.js
  src/components/BookingPanel/BookingPanel.js
  src/components/TransactionPanel/TransactionPanel.css
  src/components/TransactionPanel/TransactionPanel.helpers.js
  src/components/TransactionPanel/TransactionPanel.js
  src/components/TransactionPanel/TransactionPanel.test.js
  src/components/TransactionPanel/__snapshots__/TransactionPanel.test.js.snap
  src/containers/CheckoutPage/CheckoutPage.css
  src/containers/CheckoutPage/CheckoutPage.duck.js
  src/containers/CheckoutPage/CheckoutPage.js
  src/containers/CheckoutPage/CheckoutPage.test.js
  src/containers/CheckoutPage/CheckoutPageSessionHelpers.js
  src/containers/CheckoutPage/__snapshots__/CheckoutPage.test.js.snap
  src/containers/ListingPage/ListingPage.js
  src/containers/ListingPage/__snapshots__/ListingPage.test.js.snap
  src/containers/TransactionPage/TransactionPage.duck.js
  src/containers/TransactionPage/TransactionPage.js
  src/containers/TransactionPage/TransactionPage.test.js
  src/containers/TransactionPage/__snapshots__/TransactionPage.test.js.snap
  src/forms/StripePaymentForm/StripePaymentForm.js
  src/routeConfiguration.js
  src/translations/en.json
  src/translations/fr.json
Labels: review ok

#986 Fix yarn lock
  CHANGELOG.md
  yarn.lock
Labels: review ok

#988 Layout changes to listing and tx (enquiry) page
  CHANGELOG.md
  src/components/BookingPanel/BookingPanel.css
  src/components/BookingPanel/BookingPanel.js
  src/components/TransactionPanel/TransactionPanel.css
  src/components/TransactionPanel/TransactionPanel.helpers.js
  src/containers/ListingPage/ListingPage.css
  src/forms/BookingDatesForm/BookingDatesForm.css
Labels: review comments
