Repository sharetribe/ftw-daily, pull requests merged in 2019-06, with the labels that each got.

#1106 Fix bug in showing the review link after other party has already reviewed it
  .auditrc
  CHANGELOG.md
  src/components/ActivityFeed/ActivityFeed.js
Labels: review comments

#1111 Upgrade SDK
  CHANGELOG.md
  package.json
  yarn.lock
Labels: review comments, review ok

#1114 Clear cardtoken before redirecting
  .auditrc
  CHANGELOG.md
  src/containers/CheckoutPage/CheckoutPage.js
  src/ducks/stripe.duck.js
Labels: review comments, review ok

#1109 WiP: Confirm payment
  src/config.js
  src/containers/CheckoutPage/CheckoutPage.duck.js
  src/containers/CheckoutPage/CheckoutPage.js
  src/containers/CheckoutPage/CheckoutPage.test.js
  src/ducks/stripe.duck.js
  src/forms/StripePaymentForm/StripePaymentForm.js
Labels: in progress, review comments

#1117 Add payment expired to transaction.js
  src/containers/InboxPage/InboxPage.js
  src/translations/en.json
  src/util/transaction.js
Labels: review ok
