Repository sharetribe/ftw-daily, pull requests merged in 2019-03, with the labels that each got.

#1042 Show error if Stripe publishable key is not configured
  CHANGELOG.md
  README.md
  src/forms/PayoutDetailsForm/PayoutDetailsForm.css
  src/forms/PayoutDetailsForm/PayoutDetailsForm.js
  src/forms/StripePaymentForm/StripePaymentForm.css
  src/forms/StripePaymentForm/StripePaymentForm.js
  src/translations/en.json
Labels: review wanted

#1048 Fix empty slug
  CHANGELOG.md
  src/util/routes.js
  src/util/urlHelpers.js
  src/util/urlHelpers.test.js
Labels: review comments, review ok

#1055 Add comment about category and amenities filters not working by default
  CHANGELOG.md
  src/containers/SearchPage/README.md
  src/containers/SearchPage/SearchPage.js
Labels: in progress
