Repository sharetribe/ftw-daily, pull requests merged in 2019-08, with the labels that each got.

#1143 Fetch stripe customer relationship
  src/containers/CheckoutPage/CheckoutPage.duck.js
  src/containers/CheckoutPage/CheckoutPage.js
  src/containers/CheckoutPage/CheckoutPage.test.js
  src/containers/CheckoutPage/__snapshots__/CheckoutPage.test.js.snap
  src/forms/StripePaymentForm/StripePaymentForm.js
Labels: review ok

#1144 Update duck files
  src/ducks/index.js
  src/ducks/paymentMethods.duck.js
  src/ducks/stripe.duck.js
Labels: review ok

#1147 Create SavedCardDetails component
  src/components/IconCard/IconCard.css
  src/components/IconCard/IconCard.js
  src/components/SavedCardDetails/SavedCardDetails.css
  src/components/SavedCardDetails/SavedCardDetails.example.js
  src/components/SavedCardDetails/SavedCardDetails.js
  src/components/index.js
  src/examples.js
  src/translations/en.json
Labels: review wanted

#1145 Save payment method on PaymentMethodsPage
  src/components/SavedCardDetails/SavedCardDetails.js
  src/containers/PaymentMethodsPage/PaymentMethodsPage.css
  src/containers/PaymentMethodsPage/PaymentMethodsPage.duck.js
  src/containers/PaymentMethodsPage/PaymentMethodsPage.js
  src/containers/reducers.js
  src/forms/PaymentMethodsForm/PaymentMethodsForm.js
  src/routeConfiguration.js
  src/translations/en.json
Labels: review comments

#1150 Create new component for account settings tabs
  src/components/LayoutSideNavigation/LayoutSideNavigation.js
  src/components/LayoutWrapperAccountSettingsSideNav/LayoutWrapperAccountSettingsSideNav.js
  src/components/TabNav/TabNav.css
  src/components/index.js
  src/containers/ContactDetailsPage/ContactDetailsPage.js
  src/containers/ContactDetailsPage/__snapshots__/ContactDetailsPage.test.js.snap
  src/containers/PasswordChangePage/PasswordChangePage.js
  src/containers/PasswordChangePage/__snapshots__/PasswordChangePage.test.js.snap
  src/containers/PaymentMethodsPage/PaymentMethodsPage.js
  src/containers/PayoutPreferencesPage/PayoutPreferencesPage.js
  src/containers/PayoutPreferencesPage/__snapshots__/PayoutPreferencesPage.test.js.snap
  src/forms/PaymentMethodsForm/PaymentMethodsForm.css
Labels: review wanted

#1153 Save card after onetime payment
  src/components/FieldCheckbox/FieldCheckbox.css
  src/components/FieldCheckbox/FieldCheckbox.js
  src/components/SavedCardDetails/SavedCardDetails.js
  src/components/TransactionPanel/TransactionPanel.css
  src/components/TransactionPanel/TransactionPanel.js
  src/containers/CheckoutPage/CheckoutPage.css
  src/containers/CheckoutPage/CheckoutPage.js
  src/containers/CheckoutPage/CheckoutPage.test.js
  src/containers/CheckoutPage/__snapshots__/CheckoutPage.test.js.snap
  src/containers/PaymentMethodsPage/PaymentMethodsPage.js
  src/containers/TransactionPage/TransactionPage.duck.js
  src/containers/TransactionPage/TransactionPage.js
  src/containers/TransactionPage/__snapshots__/TransactionPage.test.js.snap
  src/ducks/paymentMethods.duck.js
  src/ducks/stripe.duck.js
  src/forms/StripePaymentForm/StripePaymentForm.css
  src/forms/StripePaymentForm/StripePaymentForm.js
  src/translations/en.json
  src/util/types.js
Labels: review comments, review ok

#1151 Use stripe config to determine US specific fields
  CHANGELOG.md
  src/ducks/stripe.duck.js
  src/forms/PayoutDetailsForm/PayoutDetailsAccountOpener.js
  src/forms/PayoutDetailsForm/PayoutDetailsAdditionalPersons.js
  src/forms/PayoutDetailsForm/PayoutDetailsBusinessProfile.js
  src/forms/PayoutDetailsForm/PayoutDetailsIndividualAccount.js
  src/forms/PayoutDetailsForm/PayoutDetailsPersonalDetails.js
Labels: review ok

#1154 Rehydrate bug: existing DOM elements were populated incorrectly
  CHANGELOG.md
  src/components/TopbarDesktop/TopbarDesktop.js
Labels: review ok

#1179 Migrate from react-helmet to react-helmet-async
  package.json
  src/app.js
  src/app.node.test.js
  src/components/Page/Page.js
  yarn.lock
Labels: review wanted

#1182 Fix FieldBirthdayInput: valueFromForm prop didn't work anymore
  CHANGELOG.md
  src/components/FieldBirthdayInput/FieldBirthdayInput.example.js
  src/components/FieldBirthdayInput/FieldBirthdayInput.js
Labels: review ok

#1183 Fix availabilityplan prop validation in EditListingAvailabilityForm
  CHANGELOG.md
  src/forms/EditListingAvailabilityForm/EditListingAvailabilityForm.example.js
  src/forms/EditListingAvailabilityForm/EditListingAvailabilityForm.js
  src/forms/EditListingAvailabilityForm/EditListingAvailabilityForm.test.js
  src/forms/EditListingAvailabilityForm/ManageAvailabilityCalendar.js
  src/forms/EditListingAvailabilityForm/__snapshots__/EditListingAvailabilityForm.test.js.snap
  src/util/types.js
Labels: review ok

#1185 Fix componentWillUnmount on ProfileSettingsForm
  CHANGELOG.md
  src/forms/ProfileSettingsForm/ProfileSettingsForm.js
Labels: review wanted
