Repository sharetribe/ftw-daily, pull requests merged in 2019-07, with the labels that each got.

#1121 Verify email automatically and redirect to landing page
  CHANGELOG.md
  src/containers/EmailVerificationPage/EmailVerificationPage.js
  src/routeConfiguration.js
Labels: review comments, review ok

#1122 Add Singapore to supported Stripe countries
  CHANGELOG.md
  src/components/StripeBankAccountTokenInputField/StripeBankAccountTokenInputField.util.js
  src/ducks/stripe.duck.js
  src/forms/PayoutDetailsForm/PayoutDetailsPersonalDetails.js
  src/stripe-config.js
  src/translations/en.json
  src/util/validators.js
Labels: review ok

#1135 Update dependencies
  CHANGELOG.md
  package.json
  src/index.js
  yarn.lock
Labels: review wanted

#1146 Add ensureStripeCustomer and ensurePaymentMethodCard
  src/util/data.js
Labels: review wanted
