Repository sharetribe/ftw-daily, pull requests merged in 2019-12, with the labels that each got.

#1232 Show states and provinces as dropdown on PayoutDetailsForm
  CHANGELOG.md
  src/forms/PayoutDetailsForm/PayoutDetailsAddress.js
  src/forms/PayoutDetailsForm/statesAndProvinces.js
  src/stripe-config.js
  src/translations/en.json
Labels: review comments, review ok

#1238 Add update Stripe account SDK call to stripe.duck.js
  src/ducks/stripe.duck.js
Labels: review ok

#1240 Make reordering easier for EditListinWizard tabs.
  src/components/EditListingAvailabilityPanel/EditListingAvailabilityPanel.js
  src/components/EditListingDescriptionPanel/EditListingDescriptionPanel.js
  src/components/EditListingFeaturesPanel/EditListingFeaturesPanel.js
  src/components/EditListingLocationPanel/EditListingLocationPanel.js
  src/components/EditListingPhotosPanel/EditListingPhotosPanel.js
  src/components/EditListingPoliciesPanel/EditListingPoliciesPanel.js
  src/components/EditListingPricingPanel/EditListingPricingPanel.js
  src/components/EditListingWizard/EditListingWizard.js
  src/components/EditListingWizard/EditListingWizardTab.js
  src/forms/EditListingAvailabilityForm/EditListingAvailabilityForm.js
  src/forms/EditListingDescriptionForm/EditListingDescriptionForm.js
  src/forms/EditListingFeaturesForm/EditListingFeaturesForm.js
  src/forms/EditListingLocationForm/EditListingLocationForm.js
  src/forms/EditListingPhotosForm/EditListingPhotosForm.js
  src/forms/EditListingPoliciesForm/EditListingPoliciesForm.js
  src/forms/EditListingPricingForm/EditListingPricingForm.js
Labels: review ok

#1231 Update API reference docs links
  CHANGELOG.md
  src/components/BookingBreakdown/LineItemBookingPeriod.js
  src/components/BookingTimeInfo/BookingTimeInfo.js
Labels: in progress
