Repository sharetribe/ftw-daily, pull requests merged in 2019-01, with the labels that each got.

#972 Manage Availability
  CHANGELOG.md
  src/components/EditListingAvailabilityPanel/EditListingAvailabilityPanel.css
  src/components/EditListingAvailabilityPanel/EditListingAvailabilityPanel.js
  src/components/EditListingWizard/EditListingWizard.css
  src/components/EditListingWizard/EditListingWizard.js
  src/components/EditListingWizard/EditListingWizardTab.js
  src/components/ManageListingCard/ManageListingCard.js
  src/components/ManageListingCard/__snapshots__/ManageListingCard.test.js.snap
  src/components/index.js
  src/containers/EditListingPage/EditListingPage.duck.js
  src/containers/EditListingPage/EditListingPage.js
  src/containers/EditListingPage/EditListingPage.test.js
  src/containers/EditListingPage/__snapshots__/EditListingPage.test.js.snap
  src/examples.js
  src/forms/EditListingAvailabilityForm/EditListingAvailabilityForm.css
  src/forms/EditListingAvailabilityForm/EditListingAvailabilityForm.example.js
  src/forms/EditListingAvailabilityForm/EditListingAvailabilityForm.js
  src/forms/EditListingAvailabilityForm/EditListingAvailabilityForm.test.js
  src/forms/EditListingAvailabilityForm/ManageAvailabilityCalendar.css
  src/forms/EditListingAvailabilityForm/ManageAvailabilityCalendar.js
  src/forms/EditListingAvailabilityForm/__snapshots__/EditListingAvailabilityForm.test.js.snap
  src/forms/index.js
  src/translations/en.json
  src/translations/fr.json
  src/util/contextHelpers.js
  src/util/data.js
  src/util/dates.js
  src/util/dates.test.js
  src/util/test-data.js
  src/util/types.js
Labels: review ok

#980 Add stripe business accounts
  CHANGELOG.md
  src/components/EditListingWizard/EditListingWizard.css
  src/components/EditListingWizard/EditListingWizard.js
  src/components/FieldRadioButton/FieldRadioButton.css
  src/components/IconAdd/IconAdd.css
  src/components/IconAdd/IconAdd.example.js
  src/components/IconAdd/IconAdd.js
  src/components/IconClose/IconClose.example.js
  src/components/IconClose/IconClose.js
  src/components/index.js
  src/containers/AuthenticationPage/AuthenticationPage.css
  src/ducks/user.duck.js
  src/examples.js
  src/forms/PayoutDetailsForm/PayoutDetailsAddress.js
  src/forms/PayoutDetailsForm/PayoutDetailsBankDetails.js
  src/forms/PayoutDetailsForm/PayoutDetailsForm.css
  src/forms/PayoutDetailsForm/PayoutDetailsForm.js
  src/forms/PayoutDetailsForm/PayoutDetailsFormCompany.js
  src/forms/PayoutDetailsForm/PayoutDetailsFormIndividual.js
  src/forms/PayoutDetailsForm/PayoutDetailsPersonalDetails.js
  src/stripe-config.js
  src/translations/en.json
  src/translations/fr.json
Labels: review ok

#992 Add Spanish translations: es.json
  CHANGELOG.md
  docs/translations.md
  src/app.js
  src/translations/es.json
Labels: review wanted

#997 Expand blockable dates to 365
  CHANGELOG.md
  src/forms/EditListingAvailabilityForm/ManageAvailabilityCalendar.js
Labels: review ok

#1000 Use env variable to enable or disable availability calendar
  CHANGELOG.md
  src/components/EditListingWizard/EditListingWizard.js
  src/components/ManageListingCard/ManageListingCard.js
  src/components/ManageListingCard/ManageListingCard.test.js
  src/config.js
  src/containers/ListingPage/ListingPage.duck.js
  src/containers/TransactionPage/TransactionPage.duck.js
Labels: review comments, review ok

#999 Update sentry
  .env-template
  CHANGELOG.md
  docs/env.md
  docs/sentry.md
  package.json
  server/log.js
  src/config.js
  src/util/log.js
  yarn.lock
Labels: review wanted

#994 Config CLI
  .env-template
  CHANGELOG.md
  README.md
  docs/customization-guide.md
  docs/env.md
  docs/translations.md
  package.json
  scripts/config.js
  scripts/translations.js
Labels: review comments

#1002 Enable limiting location autocomplete to a certain country
  CHANGELOG.md
  docs/map-providers.md
  public/static/scripts/mapbox/mapbox-sdk.js
  public/static/scripts/mapbox/mapbox-sdk.min.js
  src/components/LocationAutocompleteInput/GeocoderGoogleMaps.js
  src/components/LocationAutocompleteInput/GeocoderMapbox.js
  src/config.js
  src/util/googleMaps.js
Labels: review ok

#1005 Default to English translation if translation key is missing
  CHANGELOG.md
  docs/translations.md
  src/app.js
Labels: review ok

#1006 Add additional owners info text to PayoutDetails form
  CHANGELOG.md
  src/forms/PayoutDetailsForm/PayoutDetailsForm.css
  src/forms/PayoutDetailsForm/PayoutDetailsFormCompany.js
  src/translations/en.json
Labels: review ok

#1007 Add ownListing to listing prop type
  CHANGELOG.md
  src/components/BookingPanel/BookingPanel.js
Labels: review ok

#1008 Improve InboxPage
  src/containers/InboxPage/InboxPage.css
  src/containers/InboxPage/InboxPage.duck.js
  src/containers/InboxPage/InboxPage.js
  src/containers/InboxPage/InboxPage.test.js
  src/containers/InboxPage/__snapshots__/InboxPage.test.js.snap
Labels: review ok

#1009 Use the same FSM description format as Xstate library
  src/components/ActivityFeed/ActivityFeed.js
  src/components/BookingBreakdown/LineItemTotalPrice.js
  src/components/TransactionPanel/TransactionPanel.css
  src/components/TransactionPanel/TransactionPanel.js
  src/components/TransactionPanel/TransactionPanel.test.js
  src/components/TransactionPanel/__snapshots__/TransactionPanel.test.js.snap
  src/containers/InboxPage/InboxPage.js
  src/containers/TransactionPage/TransactionPage.duck.js
  src/util/transaction.js
  src/util/transaction.test.js
Labels: in progress

#1014 Move customization guide and testing docs to Flex Docs
  CHANGELOG.md
  README.md
  docs/README.md
  docs/customization-guide.md
  docs/deploying-to-production.md
  docs/testing.md
Labels: review ok

#1011 en translation fix for ReviewForm.reviewRatingRequired
  CHANGELOG.md
  src/translations/en.json
Labels: review ok

#1015 Move more documentation to Flex Docs
  CHANGELOG.md
  README.md
  docs/README.md
  docs/_config.yml
  docs/_layouts/default.html
  docs/assets/deploying-to-production/fork_button.png
  docs/assets/deploying-to-production/heroku-config-vars.png
  docs/assets/deploying-to-production/heroku-connect-git.png
  docs/assets/deploying-to-production/heroku-domains.png
  docs/assets/deploying-to-production/heroku-logs.png
  docs/assets/extend-listing/capacity_listing_page.png
  docs/assets/extend-listing/edit_capacity.png
  docs/assets/search-filters/desktop-filters.png
  docs/assets/search-filters/filters-panel.png
  docs/assets/search-filters/mobile-filters.png
  docs/assets/styling/styling-find-component.png
  docs/assets/translations/translations_cli.gif
  docs/ci.md
  docs/customization-checklist.md
  docs/deploying-to-production.md
  docs/extend-listing.md
  docs/extended-data.md
  docs/folder-structure.md
  docs/icons.md
  docs/improving-performance.md
  docs/redux.md
  docs/routing.md
  docs/search-filters.md
  docs/static-pages.md
  docs/styling.md
  docs/terms-of-service-and-privacy-policy.md
  docs/translations.md
Labels: review comments, review ok
