Repository sharetribe/ftw-daily, pull requests merged in 2019-05, with the labels that each got.

#1079 Don't mutate args in updatedEntities
  CHANGELOG.md
  src/util/data.js
Labels: review wanted

#1086 Move creating payment token to stripe.duck.js
  CHANGELOG.md
  src/containers/CheckoutPage/CheckoutPage.js
  src/containers/CheckoutPage/CheckoutPage.test.js
  src/containers/CheckoutPage/__snapshots__/CheckoutPage.test.js.snap
  src/ducks/stripe.duck.js
  src/forms/StripePaymentForm/StripePaymentForm.example.js
  src/forms/StripePaymentForm/StripePaymentForm.js
Labels: review wanted

#1088 Use final form in StripePaymentForm
  CHANGELOG.md
  src/containers/CheckoutPage/CheckoutPage.js
  src/containers/CheckoutPage/CheckoutPage.test.js
  src/containers/CheckoutPage/__snapshots__/CheckoutPage.test.js.snap
  src/ducks/stripe.duck.js
  src/forms/StripePaymentForm/StripePaymentForm.example.js
  src/forms/StripePaymentForm/StripePaymentForm.js
Labels: review comments, review ok

#1091 Use handleCardPayment thunk
  src/containers/CheckoutPage/CheckoutPage.js
  src/containers/CheckoutPage/CheckoutPage.test.js
  src/containers/CheckoutPage/__snapshots__/CheckoutPage.test.js.snap
  src/forms/StripePaymentForm/StripePaymentForm.css
  src/forms/StripePaymentForm/StripePaymentForm.js
Labels: review ok

#1099 Update Mapbox GL JS library to v1.0.0 and Mapbox SDK to v0.6.0
  CHANGELOG.md
  public/index.html
  public/static/scripts/mapbox/mapbox-sdk.js
  public/static/scripts/mapbox/mapbox-sdk.min.js
Labels: review ok
